---
domainName: example.com
ingressClass: nginx
certIssuer: letsencrypt-staging
certSecret: laravel-application-crt

ingress:
  name: laravel-application-staging-ingress
  allowHttp: true

app:
  image: bitnami/laravel:latest
  name: laravel-application-staging
  targetPort: 3000
  port: 80
  type: ClusterIP
  imagePullSecrets: 
  volume:
    enabled: true
    name: app-storage-volume
    mountPath: /app/gce-persistent-disk
    pdName: app-storage-disk-staging
    fsType: ext4
  env:
    enabled: true
    secretName: laravel-app-secrets-staging
    APP_ENV: test
    APP_KEY: base64:66Vnu0FtD3IIllG+ZtHmKKohBsSe74hV2jLjshR+CIg=
    APP_DEBUG: false
    APP_LOG_LEVEL: debug
    APP_URL: example.com
    DEBUGBAR_ENABLED: false
    SENTRY_LARAVEL_DSN: 

    DB_CONNECTION: mysql
    DB_HOST: localhost
    DB_PORT: 3306
    DB_DATABASE: db
    DB_USERNAME: user
    DB_PASSWORD: pass

    BROADCAST_DRIVER: log
    CACHE_DRIVER: array
    QUEUE_CONNECTION: sync
    SESSION_DRIVER: file
    SESSION_LIFETIME: 120

    REDIS_HOST: 127.0.0.1
    REDIS_PASSWORD: null
    REDIS_PORT: 6379

    PUSHER_APP_ID: 
    PUSHER_APP_KEY: 
    PUSHER_APP_SECRET: 
    PUSHER_APP_CLUSTER: mt1

    MAIL_DRIVER: 
    SENDGRID_API_KEY:                             