---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.env.secretName }}
stringData:
  APP_ENV: {{ .Values.app.env.APP_ENV }}
  APP_KEY: {{ .Values.app.env.APP_KEY }}
  APP_DEBUG: {{ .Values.app.env.APP_DEBUG }}
  APP_LOG_LEVEL: {{ .Values.app.env.APP_LOG_LEVEL }}
  APP_URL: {{ .Values.app.env.APP_URL }}
  DEBUGBAR_ENABLED: {{ .Values.app.env.DEBUGBAR_ENABLED }}
  SENTRY_LARAVEL_DSN: {{ .Values.app.env.SENTRY_LARAVEL_DSN }}

  DB_CONNECTION: {{ .Values.app.env.DB_CONNECTION }}
  DB_HOST: {{ .Values.app.env.DB_HOST }}
  DB_PORT: {{ .Values.app.env.DB_PORT }}
  DB_DATABASE: {{ .Values.app.env.DB_DATABASE }}
  DB_USERNAME: {{ .Values.app.env.DB_USERNAME }}
  DB_PASSWORD: {{ .Values.app.env.DB_PASSWORD }}

  BROADCAST_DRIVER: {{ .Values.app.env.BROADCAST_DRIVER }}
  CACHE_DRIVER: {{ .Values.app.env.CACHE_DRIVER }}
  QUEUE_CONNECTION: {{ .Values.app.env.QUEUE_CONNECTION }}
  SESSION_DRIVER: {{ .Values.app.env.SESSION_DRIVER }}
  SESSION_LIFETIME: {{ .Values.app.env.SESSION_LIFETIME }}

  REDIS_HOST: {{ .Values.app.env.REDIS_HOST }}
  REDIS_PASSWORD: {{ .Values.app.env.REDIS_PASSWORD }}
  REDIS_PORT: {{ .Values.app.env.REDIS_PORT }}

  PUSHER_APP_ID: {{ .Values.app.env.PUSHER_APP_ID }}
  PUSHER_APP_KEY: {{ .Values.app.env.PUSHER_APP_KEY }}
  PUSHER_APP_SECRET: {{ .Values.app.env.PUSHER_APP_SECRET }}
  PUSHER_APP_CLUSTER: {{ .Values.app.env.PUSHER_APP_CLUSTER }}
  
  MAIL_DRIVER: {{ .Values.app.env.MAIL_DRIVER }}
  SENDGRID_API_KEY: {{ .Values.app.env.SENDGRID_API_KEY }}

