---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.app.name }}-ingress"
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
    certmanager.k8s.io/cluster-issuer: {{ .Values.certIssuer }}
spec:
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
        - backend:
            serviceName: {{ .Values.app.name }}
            servicePort: {{ .Values.app.port }}
          path: /
  tls:
    - hosts:
        - {{ .Values.domainName }}
      secretName: {{ .Values.certSecret }}
