---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  type: {{ .Values.app.type }}
  ports:
    - name: http
      port: {{ .Values.app.port }} 
      targetPort: {{ .Values.app.targetPort }}
  selector:
    app: {{ .Values.app.name }}